name: Java CI with Gradle

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@417ae3ccd767c252f5661f1ace9f835f9654f2b5 # v3.1.0

      - name: Run build with Gradle Wrapper
        run: ./gradlew build

      - name: Upload built JAR (Fabric)
        uses: actions/upload-artifact@v3
        with:
          name: iris-artifacts
          path: build/libs
